// music table from DB
const data = [
    { name:  "Pink Moon", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=cbbilwIZMGI&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=1" },
{ name:  "Place to Be", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=obOWSCmzEAY&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=2" },
{ name:  "Road", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=oQJmaKBcMzo&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=3" },
{ name:  "Which Will", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=A0NDxRNdQKk&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=4" },
{ name:  "Horn", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=GIv-vjylk5A&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=5" },
{ name:  "Things Behind the Sun", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=v2myMNzPuGE&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=6" },
{ name:  "Know", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=Y-eHBUudkcY&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=7" },
{ name:  "Parasite", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=2_hN3otvC6g&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=8" },
{ name:  "Free Ride", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=l09L45RM2RI&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=9" },
{ name:  "Harvest Breed", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=kCy25ylGW_E&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=10" },
{ name:  "From the Morning", album: "Pink Moon", artist: "Nick Drake", link: "https://www.youtube.com/watch?v=-kFAf7tENdQ&list=PLnif9Rfb5Adn9YCMvQT50xkO1ZASc-yxB&index=11" },
{ name:  "Waiting On The World To Change", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=Y2CFPaLxN5w&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=1" },
{ name:  "I Don´t Trust Myself (With Loving You)", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=kKGmMa7tfY8&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=2" },
{ name:  "Belief", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=vmkTMAc4X_k&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=3" },
{ name:  "Gravity", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=tPzusaFIzLU&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=4" },
{ name:  "The Heart of Life", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=Nl1DgzC3uMw&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=5" },
{ name:  "Vultures", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=j-WdGdCRCVU&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=6" },
{ name:  "Stop This Train", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=unq_Tz5Y610&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=7" },
{ name:  "Slow Dancing in a Burning Room", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=9Kx2Sq3bHu4&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=8" },
{ name:  "Bold as Love", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=Jn9TV6XgNN8&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=9" },
{ name:  "Dreaming with a Broken Heart", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=zl-_5pB7fgo&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=10" },
{ name:  "In Repair", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=8H7FKp5FqoQ&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=11" },
{ name:  "I´m Gonna Find Another You", album: "Continuum", artist: "John Mayer", link: "https://www.youtube.com/watch?v=met6gypk2lA&list=PLCzJErxNB-OlQKppqLK5u7Opa1MIiYNR_&index=12" },
{ name:  "Airbag", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=jNY_wLukVW0&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=1" },
{ name:  "Paranoid Android", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=YTH8cxXBGBo&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=2" },
{ name:  "Subterranean Homesick Alien", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=_fTWmUlTEqE&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=3" },
{ name:  "Exit Music (For A Film)", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=Bf01riuiJWA&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=4" },
{ name:  "Let Down", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=duBCwvC1kP4&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=5" },
{ name:  "Karma Police", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=4IJI6soiQhI&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=6" },
{ name:  "Fitter Happier", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=O4SzvsMFaek&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=7" },
{ name:  "Electioneering", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=3DtgWrFTtQk&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=8" },
{ name:  "Climbing Up The Walls", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=XX4EpkR-Sp4&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=9" },
{ name:  "No Surprises", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=LBt60dfwEBY&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=10" },
{ name:  "Lucky", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=yuZYQvvLXVY&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=11" },
{ name:  "The Tourist", album: "OK Computer", artist: "Radiohead", link: "https://www.youtube.com/watch?v=HkgzObf8uVU&list=PLiN-7mukU_REVs4VvfFoZPb15d41ETgIZ&index=12" },
{ name:  "Smells Like Teen Spirit", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=iKyszBuLIo4&list=PLD2955310D784B02B&index=1" },
{ name:  "In Bloom", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=LTyNvD8Jaos&list=PLD2955310D784B02B&index=2" },
{ name:  "Come as You Are", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=9qkibSrgXXQ&list=PLD2955310D784B02B&index=3" },
{ name:  "Breed", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=lW2NgFwLhtU&list=PLD2955310D784B02B&index=4" },
{ name:  "Lithium", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=kgpSzdON2CE&list=PLD2955310D784B02B&index=5" },
{ name:  "Polly", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=h5cZvNWxnho&list=PLD2955310D784B02B&index=6" },
{ name:  "Territorial Pissings", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=bm6Iz-I5OmQ&list=PLD2955310D784B02B&index=7" },
{ name:  "Drain You", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=wPsJIOOolWU&list=PLD2955310D784B02B&index=8" },
{ name:  "Lounge Act", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=wZuoMR-rXOg&list=PLD2955310D784B02B&index=9" },
{ name:  "Stay Away", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=k2kRE_27fu0&list=PLD2955310D784B02B&index=10" },
{ name:  "On a Plain", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=Ucxu5Ny4S9E&list=PLD2955310D784B02B&index=11" },
{ name:  "Something in the Way", album: "Nevermind", artist: "Nirvana", link: "https://www.youtube.com/watch?v=oqz7VC3VIF4&list=PLD2955310D784B02B&index=12" },
{ name:  "Love Struck Baby", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=-lBZTtoJ3t0&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=1" },
{ name:  "Pride and Joy", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=Z1Pu1Lq1Hfs&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=2" },
{ name:  "Texas Flood", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=mbjzRcKXyLU&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=3" },
{ name:  "Tell Me", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=ItcT7uYtUKk&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=4" },
{ name:  "Testify", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=zc0V1HheVD4&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=5" },
{ name:  "Rude Mood", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=dBA_r6sLphg&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=6" },
{ name:  "Mary Had A Little Lamb", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=TkK7CyeKaoY&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=7" },
{ name:  "Dirty Pool", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=P6HUYXPIeKc&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=8" },
{ name:  "I´m Cryin", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=mk6MTaEsEYo&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=9" },
{ name:  "Lenny", album: "Texas Flood", artist: "Stevie Ray Vaughan", link: "https://www.youtube.com/watch?v=5bgaVGZHRO8&list=PL02pDPRbhcyaas4VyaJCk9CszCZ88-_3F&index=10" },
{ name:  "Every Day I Have the Blues", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=0RfAHm-HRqE&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=11" },
{ name:  "Sweet Little Angel", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=tBGFUz8g2dI&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=10" },
{ name:  "It´s My Own Fault", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=30UsZP2tiO4&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=8" },
{ name:  "How Blue Can You Get?", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=phqxKolsBRg&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=7" },
{ name:  "Please Love Me", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=qTfmrp4ZE-g&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=6" },
{ name:  "You Upset Me Baby", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=9nFDH6Uiv4k&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=5" },
{ name:  "Worry, Worry", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=3Dkk47n--cs&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=4" },
{ name:  "Woke Up This Mornin´", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=tbOkh2TUO5U&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=3" },
{ name:  "You Done Lost Your Good Thing Now", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=okNXLdF06co&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=2" },
{ name:  "Help the Poor", album: "Live at the Regal", artist: "B.B. King", link: "https://www.youtube.com/watch?v=o0C0Bhc6cLM&list=PLEkQvDfHXcEXqe6_i5xGm73yL74Z_Wiyw&index=1" },
{ name:  "Allegro ma non troppo, un poco maestoso", album: "Symphony No. 9 in D Minor, Op. 125 - Choral", artist: "Ludwig van Beethoven", link: "https://www.youtube.com/watch?v=1XT4T9b7Q4w&list=OLAK5uy_m673adVB1BQoqXap6dIStLRfjRkZG7uKM&index=1" },
{ name:  "Molto vivace - Presto", album: "Symphony No. 9 in D Minor, Op. 125 - Choral", artist: "Ludwig van Beethoven", link: "https://www.youtube.com/watch?v=J3yzhkw_XJQ&list=OLAK5uy_m673adVB1BQoqXap6dIStLRfjRkZG7uKM&index=2" },
{ name:  "Adagio molto e cantabile - Andante moderato - Adagio", album: "Symphony No. 9 in D Minor, Op. 125 - Choral", artist: "Ludwig van Beethoven", link: "https://www.youtube.com/watch?v=Iqu_51trOVI&list=OLAK5uy_m673adVB1BQoqXap6dIStLRfjRkZG7uKM&index=3" },
{ name:  "Presto - Allegro assai - Ode to Joy", album: "Symphony No. 9 in D Minor, Op. 125 - Choral", artist: "Ludwig van Beethoven", link: "https://www.youtube.com/watch?v=tO2bOCWrYw0&list=OLAK5uy_m673adVB1BQoqXap6dIStLRfjRkZG7uKM&index=4" },
{ name:  "Women", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=Bn-3DfJgA7s&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=5" },
{ name:  "Prison", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=yN5WTZCIdtE&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=7" },
{ name:  "Africa", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=Nn4IJbwdqeM&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=4" },
{ name:  "Mafia Club", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=zK3zrVykxEc&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=6" },
{ name:  "Mudbone", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=AOOAb56XWuU&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=1" },
{ name:  "Freebase", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=mPSLfCZ_U-Y&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=3" },
{ name:  "Hospital", album: "Live on the Sunset Strip", artist: "Richard Pryor", link: "https://www.youtube.com/watch?v=FrTrCnE7xo4&list=PL2MtElzTEi6nNrc_6DVDfdkl7DaJTBsUy&index=2" },
{ name:  "Class Clown - Bi-Labial Fricative / Attracting Attention / Squeamish", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=qKPPJtpedg8&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=7" },
{ name:  "Wasted Time - Sharing A Swallow", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=iAPA-rBmIdQ&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=6" },
{ name:  "Values (How Much Is That Dog Crap In The Window)", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=O_kUg10yoEk&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=5" },
{ name:  "I Used To Be Irish Catholic", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=HcrkHnelxq0&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=3" },
{ name:  "The Confessional", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=BLlKCVVd3hk&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=2" },
{ name:  "Special Dispensation - Heaven, Hell, Purgatory And Limbo", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=AYZYVr0Lcww&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=1" },
{ name:  "Heavy Mysteries", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=PIE45IZHLPc&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=4" },
{ name:  "Muhammad Ali - America The Beautiful", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=xrSQzLIENlU&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=8" },
{ name:  "Seven Words You Can Never Say On Television", album: "Class Clown", artist: "George Carlin", link: "https://www.youtube.com/watch?v=uoW42kJVgs0&list=PL2MtElzTEi6lLw1cFthQ_lAzsZTtQU47v&index=9" },
{ name:  "Folsom Prison Blues", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=U9uk6NHK-AE&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=1" },
{ name:  "Dark As The Dungeon", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=OFjBLdyssjc&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=2" },
{ name:  "I Still Miss Someone", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=0GM-1N8TfHE&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=3" },
{ name:  "Cocaine Blues", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=0VZuA7iJY4Y&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=4" },
{ name:  "25 Minutes To Go", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=dm5ghpXzxl0&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=5" },
{ name:  "Orange Blossom Special", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=WkMB3RitBSE&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=6" },
{ name:  "The Long Black Veil", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=c0OSboEOtRQ&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=7" },
{ name:  "Send A Picture Of Mother", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=0JUSmwGl4T4&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=8" },
{ name:  "The Wall", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=FipYtoZfl7M&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=9" },
{ name:  "Dirty Old Egg-Sucking Dog", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=jeudEqVhJOM&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=10" },
{ name:  "Flushed From The Bathroom Of Your Heart", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=q3wyAzjlE9Y&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=11" },
{ name:  "Jackson", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=FPynO42XFRw&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=12" },
{ name:  "Give My Love To Rose", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=Mqe2kcRZo5I&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=13" },
{ name:  "I Got Stripes", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=AmwJBxZgud4&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=14" },
{ name:  "Green, Green Grass Of Home", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=SLfxsneyfnY&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=15" },
{ name:  "Greystone Chapel", album: "At Folsom Prison", artist: "Johnny Cash", link: "https://www.youtube.com/watch?v=fGMVRoXelNs&list=PLiN-7mukU_REOclREjfMGotXFDlADw5DZ&index=16" },
{ name:  "Coat of Many Colors", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=KFbYFHaigSk&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=1" },
{ name:  "Traveling Man", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=UzPHsYMFja8&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=2" },
{ name:  "My Blue Tears", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=s4bnZ3TvHcw&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=3" },
{ name:  "If I Lose My Mind", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=zLQClAAOHu0&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=4" },
{ name:  "The Mystery Of The Mystery", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=Udw6V6P-cuI&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=5" },
{ name:  "She Never Met A Man (She Didn´t Like)", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=oEva53Jc_hA&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=6" },
{ name:  "Early Morning Breeze", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=9n6HGWkldbw&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=7" },
{ name:  "The Way I See You", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=LL7YjAadTNo&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=8" },
{ name:  "Here I Am", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=RindBGXOmC4&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=9" },
{ name:  "A Better Place To Live", album: "Coat of Many Colors", artist: "Dolly Parton", link: "https://www.youtube.com/watch?v=m-p8g2fBIjQ&list=OLAK5uy_k5QFQ8QgmhwVunSjQKYiJqtBROA__CB8E&index=10" },
{ name:  "Who You Say I Am", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=lKw6uqtGFfo&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=1" },
{ name:  "You Are Life", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=Tw8-g7a3T7k&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=2" },
{ name:  "The Passion", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=1JIOna6Bj9Y&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=3" },
{ name:  "God So Loved", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=E7i6c54KEfc&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=4" },
{ name:  "Be Still", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=H7pJb49vVQY&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=5" },
{ name:  "Remembrance", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=U9kbdFCSrFU&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=6" },
{ name:  "Valentine", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=J3AbRVJRrC4&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=7" },
{ name:  "Touch Of Heaven", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=nxxr47zEUxE&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=8" },
{ name:  "Lettered Love", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=yP-Pcz7OHgk&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=9" },
{ name:  "The Lord´s Prayer", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=nCxqjEz5hJ4&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=10" },
{ name:  "New Wine", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=1ozGKlOzEVc&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=11" },
{ name:  "So Will I (100 Billion X)", album: "There Is More", artist: "Hillsong", link: "https://www.youtube.com/watch?v=GfVd5x9W1Xc&list=PLTnuUe-aRkQ7jG7fTmFEb97fHKQ1GZZbb&index=12" },
{ name:  "Give Life Back To Music", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=IluRBvnYMoY&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=1" },
{ name:  "The Game Of Love", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=ajGKWk0auOc&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=2" },
{ name:  "Giorgio By Moroder", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=zhl-Cs1-sG4&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=3" },
{ name:  "Within", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=cuj__JnGWLg&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=4" },
{ name:  "Instant Crush", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=a5uQMwRMHcs&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=5" },
{ name:  "Lose Yourself To Dance", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=NF-kLy44Hls&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=6" },
{ name:  "Touch", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=0Gkhol2Q1og&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=7" },
{ name:  "Get Lucky", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=5NV6Rdv1a3I&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=8" },
{ name:  "Beyond", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=3T0NqvdUiWI&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=9" },
{ name:  "Motherboard", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=wz7YiQdNmZ8&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=10" },
{ name:  "Fragments Of Time", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=_ScM9pKlCfo&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=11" },
{ name:  "Doin´ It Right", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=LL-gyhZVvx0&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=12" },
{ name:  "Contact", album: "Random Access Memories", artist: "Daft Punk", link: "https://www.youtube.com/watch?v=JI5noh4OyXc&list=PLSbDLF8wQ3oKcstd9ybCSv2lNm_8NTYkI&index=13" },
{ name:  "Xtal", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=sWcLccMuCA8&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=1" },
{ name:  "Tha", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=N3G7JPTVVEQ&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=2" },
{ name:  "Pulsewidth", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=OtAweb0IV14&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=3" },
{ name:  "Ageispolis", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=bdWIwpTS48s&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=4" },
{ name:  "I", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=KqnezE0qLSM&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=5" },
{ name:  "Green Calx", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=6yROS-zZqFU&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=6" },
{ name:  "Heliosphan", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=Xxk-ryO6J2I&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=7" },
{ name:  "We Are The Music Makers", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=4acK8W65jAE&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=8" },
{ name:  "Schottkey 7th Path", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=22x8jxh4aVw&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=9" },
{ name:  "Ptolemy", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=dBubcKr93K0&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=10" },
{ name:  "Hedphelym", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=9gbSs6vAs_w&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=11" },
{ name:  "Delphium", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=W4YVXY5YKAE&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=12" },
{ name:  "Actium", album: "Selected Ambient Works 85-92", artist: "Aphex Twin", link: "https://www.youtube.com/watch?v=pLxNh-qDIvg&list=PLiN-7mukU_RFooOYRV24OVaorPdJNcvSS&index=13" },
{ name:  "Speak To Me", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=HW-lXjOyUWo&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=1" },
{ name:  "Breathe (In The Air)", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=Vddl9TK5RqU&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=2" },
{ name:  "On The Run", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=2sUyk5zSbhM&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=3" },
{ name:  "Time", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=pgXozIma-Oc&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=4" },
{ name:  "The Great Gig In The Sky", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=mPGv8L3a_sY&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=5" },
{ name:  "Money", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=rwPM01cbQBc&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=6" },
{ name:  "Us And Them", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=GKiLEgAzFDQ&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=7" },
{ name:  "Any Colour You Like", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=_83urK9rO4U&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=8" },
{ name:  "Brain Damage", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=BhYKN21olBw&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=9" },
{ name:  "Eclipse", album: "The Dark Side of the Moon", artist: "Pink Floyd", link: "https://www.youtube.com/watch?v=9wjZrswriz0&list=PL3PhWT10BW3Urh8ZXXpuU9h526ChwgWKy&index=10" },
{ name:  "1/1.", album: "Music for Airports", artist: "Brian Eno", link: "https://www.youtube.com/watch?v=LKZ3fGR2SDY&list=OLAK5uy_mfRTetqFB_MtRhjeOxR5tp0uVfK1YH-Sw&index=1" },
{ name:  "2/1.", album: "Music for Airports", artist: "Brian Eno", link: "https://www.youtube.com/watch?v=pgnZ4wylW8k&list=OLAK5uy_mfRTetqFB_MtRhjeOxR5tp0uVfK1YH-Sw&index=2" },
{ name:  "1/2.", album: "Music for Airports", artist: "Brian Eno", link: "https://www.youtube.com/watch?v=R4S8be2xlD8&list=OLAK5uy_mfRTetqFB_MtRhjeOxR5tp0uVfK1YH-Sw&index=3" },
{ name:  "2/2.", album: "Music for Airports", artist: "Brian Eno", link: "https://www.youtube.com/watch?v=C4kBbTlvoN4&list=OLAK5uy_mfRTetqFB_MtRhjeOxR5tp0uVfK1YH-Sw&index=4" },
{ name:  "Like A Rolling Stone", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=IwOfCgkyEj0&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=1" },
{ name:  "Tombstone Blues", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=ag-Esuy44ks&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=2" },
{ name:  "It Takes A Lot To Laugh, It Takes A Train To Cry", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=SN1ACh8lzHg&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=3" },
{ name:  "From A Buick 6", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=qBRK9KIx8SM&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=4" },
{ name:  "Ballad Of A Thin Man", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=we37yX3zpKA&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=5" },
{ name:  "Queen Jane Approximately", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=5-ZmD3sCFcE&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=6" },
{ name:  "Highway 61 Revisited", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=8hr3Stnk8_k&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=7" },
{ name:  "Just Like Tom Thumb´s Blues", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=doIMYvZyo_k&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=8" },
{ name:  "Desolation Row", album: "Highway 61 Revisited", artist: "Bob Dylan", link: "https://www.youtube.com/watch?v=hUvcWXTIjcU&list=PLXRKTcRs-Xs7rr36o5_Cs7fBn8B7KsmRG&index=9" },
{ name:  "All I Want", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=G5084WbyZM8&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=1" },
{ name:  "My Old Man", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=zREpjywwJpo&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=2" },
{ name:  "Little Green", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=HTxUrDtoPP0&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=3" },
{ name:  "Carey", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=D_r4fsSjqqU&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=4" },
{ name:  "Blue", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=Nu7aOan-lds&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=5" },
{ name:  "California", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=Ds517r3KrjY&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=6" },
{ name:  "This Flight Tonight", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=AD0dRjq4m20&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=7" },
{ name:  "River", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=ozn8UJvrLhU&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=8" },
{ name:  "A Case Of You", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=jqYpK3CFmMk&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=9" },
{ name:  "The Last Time I Saw Richard", album: "Blue", artist: "Joni Mitchell", link: "https://www.youtube.com/watch?v=y4WVZncHaLo&list=PL5g1nz_E8zidoHkFPKDY97zQna1h_kcI0&index=10" },
{ name:  "Introduction To James Brown", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=uLp42_RacFw&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=1" },
{ name:  "I´ll Go Crazy", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=Xtc_Kaw3V0Y&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=2" },
{ name:  "Try Me", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=WDa8dW8ULzE&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=3" },
{ name:  "Think", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=4b9oUx5F3zk&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=4" },
{ name:  "I Don´t Mind", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=zFg_T8CfWpk&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=5" },
{ name:  "Lost Someone Pt.1", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=u-Ty5QKI1eY&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=6" },
{ name:  "Lost Someone Pt.2", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=u-Ty5QKI1eY&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=6" },
{ name:  "Medley", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=q79XUrkSyzU&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=7" },
{ name:  "Night Train", album: "Live at the Apollo", artist: "James Brown", link: "https://www.youtube.com/watch?v=m35bbyzR2N0&list=PLowQCq3Ss89iBOasAahhcHl0FEg078bFE&index=8" },
{ name:  "P. Funk (Wants To Get Funked Up)", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=f_R3c2TIV-E&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=1" },
{ name:  "Mothership Connection (Star Child)", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=kvyNe7f7WhA&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=2" },
{ name:  "Unfunky UFO", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=jjQ4iYh039g&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=3" },
{ name:  "Supergroovalisticprosifunkstication", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=ihzjHEWflw0&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=4" },
{ name:  "Handcuffs", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=fvaSXs5Mfq8&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=5" },
{ name:  "Give Up The Funk (Tear The Roof Off The Sucker)", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=3HU-KdHmYeA&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=6" },
{ name:  "Night Of The Thumpasorus Peoples", album: "Mothership Connection", artist: "Parliament", link: "https://www.youtube.com/watch?v=0i37GEfu7VM&list=PLNPGM2D7aODe-1Pj5gotao0NOhtpFh8Pb&index=7" },
{ name:  "Wesley´s Theory", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=l9fN-8NjrvI&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=1" },
{ name:  "For Free? (Interlude)", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=qh4nXtTpTEE&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=2" },
{ name:  "King Kunta", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=g0NVaX8DRN4&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=3" },
{ name:  "Institutionalized", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=7L1POXocFIQ&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=4" },
{ name:  "These Walls", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=AHNK4k3Cr24&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=5" },
{ name:  "U", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=XGC4QpDIpJc&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=6" },
{ name:  "Alright", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=67vr-3kpX3Q&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=7" },
{ name:  "For Sale? (Interlude)", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=RdCepOB4BV8&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=8" },
{ name:  "Momma", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=q1AOP6NtGuc&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=9" },
{ name:  "Hood Politics", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=iIsHg3BHpB0&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=10" },
{ name:  "How Much A Dollar Cost", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=y8kEiL81_R4&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=11" },
{ name:  "Complexion (A Zulu Love)", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=Wt4dUK4uce0&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=12" },
{ name:  "The Blacker The Berry", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=VdPtVZDspIY&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=13" },
{ name:  "You Ain´t Gotta Lie (Momma Said)", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=78bSAKX_4vs&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=14" },
{ name:  "I", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=tt2-GsPA9kk&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=15" },
{ name:  "Mortal Man", album: "To Pimp a Butterfly", artist: "Kendrick Lamar", link: "https://www.youtube.com/watch?v=axwpgn3GRMs&list=PL8YH4mOwWryUO4kxV36tPqkiaAr4_oJe5&index=16" },
{ name:  "The Illest Villains", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=0onU04uk2EE&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=1" },
{ name:  "Accordion", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=bGCHT6fIEBw&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=2" },
{ name:  "Meat Grinder", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=FoasIcgem0w&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=3" },
{ name:  "Bistro", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=ziDFbUtMF0I&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=4" },
{ name:  "Raid", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=Y8eopWPE0Vg&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=5" },
{ name:  "America´s Most Blunted", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=HgVdmbAfDLQ&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=6" },
{ name:  "Sickfit (Inst.)", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=hFhFkrgYkuY&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=7" },
{ name:  "Rainbows", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=pXbH6yCxDVc&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=8" },
{ name:  "Curls", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=tv2q9vQ7GOI&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=9" },
{ name:  "Do Not Fire! (Inst.)", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=_MgOsVhuDGw&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=10" },
{ name:  "Money Folder", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=DV7biH2ZNj4&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=11" },
{ name:  "Shadows Of Tomorrow", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=lkW3jsz0Gnc&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=12" },
{ name:  "Operation Lifesaver AKA Mint Test", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=V0rNuyAMfvo&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=13" },
{ name:  "Figaro", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=I4P5RR4jPGg&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=14" },
{ name:  "Hardcore Hustle", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=Ohe_YyURqjc&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=15" },
{ name:  "Strange Ways", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=x8QylSXfwYc&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=16" },
{ name:  "Fancy Clown", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=yEYCCiXLPTw&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=17" },
{ name:  "Eye", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=4hw2XL7LlyY&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=18" },
{ name:  "Supervillain Theme (Inst.)", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=tJPaQC68xL0&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=19" },
{ name:  "All Caps", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=NPiAK33CfxQ&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=20" },
{ name:  "Great Day", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=yK-6yAt3c-U&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=21" },
{ name:  "Rhinestone Cowboy", album: "Madvillainy", artist: "Madvillain", link: "https://www.youtube.com/watch?v=WoxHqRPvZJE&list=PLDUEjoBVMbh9dHRr9m_TZ_jBFcv14c3p8&index=22" },
{ name:  "So What", album: "Kind of Blue", artist: "Miles Davis", link: "https://www.youtube.com/watch?v=ylXk1LBvIqU&list=PLrhkpF1bKMG_D2sxTpxG63WGmIxYGB-Jt&index=1" },
{ name:  "Freddie Freeloader", album: "Kind of Blue", artist: "Miles Davis", link: "https://www.youtube.com/watch?v=ZZcuSBouhVA&list=PLrhkpF1bKMG_D2sxTpxG63WGmIxYGB-Jt&index=2" },
{ name:  "Blue In Green", album: "Kind of Blue", artist: "Miles Davis", link: "https://www.youtube.com/watch?v=TLDflhhdPCg&list=PLrhkpF1bKMG_D2sxTpxG63WGmIxYGB-Jt&index=3" },
{ name:  "All Blues", album: "Kind of Blue", artist: "Miles Davis", link: "https://www.youtube.com/watch?v=-488UORrfJ0&list=PLrhkpF1bKMG_D2sxTpxG63WGmIxYGB-Jt&index=4" },
{ name:  "Flamenco Sketches", album: "Kind of Blue", artist: "Miles Davis", link: "https://www.youtube.com/watch?v=nTwp1sgUJrM&list=PLrhkpF1bKMG_D2sxTpxG63WGmIxYGB-Jt&index=5" },
{ name:  "Part 1 – Acknowledgement", album: "A Love Supreme", artist: "John Coltrane", link: "https://www.youtube.com/watch?v=TMvbUKqWYEs&list=PLWvco6AqKzf2OhGoRTyGO3OKQ42sAZFJe&index=1" },
{ name:  "Part 2 - Resolution", album: "A Love Supreme", artist: "John Coltrane", link: "https://www.youtube.com/watch?v=9o2TSdDPlUQ&list=PLWvco6AqKzf2OhGoRTyGO3OKQ42sAZFJe&index=2" },
{ name:  "Part 3 - Pursuance", album: "A Love Supreme", artist: "John Coltrane", link: "https://www.youtube.com/watch?v=rExeNEjbJwk&list=PLWvco6AqKzf2OhGoRTyGO3OKQ42sAZFJe&index=3" },
{ name:  "Part 4 - Psalm", album: "A Love Supreme", artist: "John Coltrane", link: "https://www.youtube.com/watch?v=yjZc7KIFlNs&list=PLWvco6AqKzf2OhGoRTyGO3OKQ42sAZFJe&index=4" },
{ name:  "The More We Get Together", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=4crwVqxsVO0&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=1" },
{ name:  "Down By The Bay", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=DWKVKfk6e40&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=2" },
{ name:  "Brush Your Teeth", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=YXYQTdcJtdY&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=3" },
{ name:  "Robin In The Rain", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=Tt8juSJ8luk&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=4" },
{ name:  "Five Little Frogs", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=n-dgauH3WrM&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=5" },
{ name:  "I Wonder If I´m Growing", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=ODb_Tr-wg3Q&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=6" },
{ name:  "Aikendrum", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=koA9DXAnSN8&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=7" },
{ name:  "Bumping Up And Down", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=IfD7iHGYugQ&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=8" },
{ name:  "Must Be Santa", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=eoToNQbfEFo&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=9" },
{ name:  "Willoughby Wallaby Woo", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=8P2LSwwPBuo&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=10" },
{ name:  "Spider On The Floor", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=iWBkqDhDByY&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=11" },
{ name:  "Baa Baa Black Sheep", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=NqwnUqQI2J4&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=12" },
{ name:  "Going To The Zoo", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=kMJbzCZrR_0&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=13" },
{ name:  "My Dreydel", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=EUpnvceJqKA&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=14" },
{ name:  "Peanut Butter Sandwich", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=4lbnfK9tXWs&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=15" },
{ name:  "Five Little Pumpkins", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=HAHZCJpCeDs&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=16" },
{ name:  "The Sharing Song", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=Aa--lnfw-GY&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=17" },
{ name:  "Mr. Sun", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=593B-bVPWjw&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=18" },
{ name:  "Old MacDonald Had A Band", album: "Singable Songs for the Very Young", artist: "Raffi", link: "https://www.youtube.com/watch?v=6RC8k0LAUTY&list=OLAK5uy_nXapO3ixqFGjOGHsaR0yNl2VdYm_1keq8&index=19" },
{ name:  "Chan Chan", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=fE4Sf7vXgbo&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=1" },
{ name:  "De Camino A La Vereda", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=_RrVQ9mFjq8&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=2" },
{ name:  "El Cuarto De Tula", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=gaKKELQWhbs&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=3" },
{ name:  "Pueblo Nuevo", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=OagCWe_oer8&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=4" },
{ name:  "Dos Gardenias", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=fugRvM6s5fc&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=5" },
{ name:  "¿Y Tú Qué Has Hecho?", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=LhXfgENBxII&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=6" },
{ name:  "Veinte Años", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=d2vBh6_h7WE&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=7" },
{ name:  "El Carretero", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=VACtwLtDHd0&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=8" },
{ name:  "Candela", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=4_7zkXv17QE&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=9" },
{ name:  "Amor De Loca Juventud", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=RsSufRnVo2A&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=10" },
{ name:  "Orgullecida", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=G00wyxo7UPE&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=11" },
{ name:  "Murmullo", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=HbyAIfjCLMA&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=12" },
{ name:  "Buena Vista Social Club", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=8TdC59g-u1U&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=13" },
{ name:  "La Bayamesa", album: "Buena Vista Social Club", artist: "Buena Vista Social Club", link: "https://www.youtube.com/watch?v=alB2Q2m64es&list=PLetv3SCC-r3bPinnDE7jWxKPJc-mpEalB&index=14" },
{ name:  "War Pigs", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=rmleuQP5owA&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=1" },
{ name:  "Paranoid", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=5mvnvM5YjVU&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=2" },
{ name:  "Planet Caravan", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=JWY-0kWcoos&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=3" },
{ name:  "Iron Man", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=WYgJmSz5Gtk&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=4" },
{ name:  "Electric Funeral", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=4aJT2p2_pDk&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=5" },
{ name:  "Hand Of Doom", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=wb2KIlo87y4&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=6" },
{ name:  "Rat Salad", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=AwB5WVLWEU8&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=7" },
{ name:  "Fairies Wear Boots", album: "Paranoid", artist: "Black Sabbath", link: "https://www.youtube.com/watch?v=VLBfPSS-x5U&list=PLo2VF3ux4qcZ6b7vL7SVhBEK_NAbKzsoD&index=8" },
{ name:  "Battery", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=jMOFeo9ebkQ&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=1" },
{ name:  "Master Of Puppets", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=DP6i06npRls&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=2" },
{ name:  "The Thing That Should Not Be", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=N3TXP0fnWt4&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=3" },
{ name:  "Welcome Home (Sanitarium)", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=en83j4fKTmY&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=4" },
{ name:  "Disposable Heroes", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=rccAS7u_gwg&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=5" },
{ name:  "Leper Messiah", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=s10Y1nLgd7w&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=6" },
{ name:  "Orion", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=nZMD7yUlwyI&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=7" },
{ name:  "Damage, Inc.", album: "Master of Puppets", artist: "Metallica", link: "https://www.youtube.com/watch?v=tRxYCNohYNs&list=PLvyFvczmiBrunjTBsQ5jypBacIcCMDw6P&index=8" },
{ name:  "Wanna Be Startin´ Somethin", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=8KWf_-ofYgI&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=1" },
{ name:  "Baby Be Mine", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=COSMzAASQj4&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=2" },
{ name:  "The Girl Is Mine", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=SX5vM6F57_E&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=3" },
{ name:  "Thriller", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=Z85lxckrtzg&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=4" },
{ name:  "Beat It", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=kOn-HdEg6AQ&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=5" },
{ name:  "Billie Jean", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=Kr4EQDVETuA&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=6" },
{ name:  "Human Nature", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=oqLpko9Gprs&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=7" },
{ name:  "P.Y.T. (Pretty Young Thing)", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=y32ejtuxSjM&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=8" },
{ name:  "The Lady In My Life", album: "Thriller", artist: "Michael Jackson", link: "https://www.youtube.com/watch?v=Eqcw7tLnrd8&list=PLFAcddgaFN8zqIJrTakvM9qWnR7iIrXnj&index=9" },
{ name:  "Come Together", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=oolpPmuK2I8&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=1" },
{ name:  "Something", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=VWO3nEuWo4k&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=2" },
{ name:  "Maxwell´s Silver Hammer", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=mJag19WoAe0&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=3" },
{ name:  "Oh! Darling", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=9BznFjbcBVs&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=4" },
{ name:  "Octopus´s Garden", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=De1LCQvbqV4&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=5" },
{ name:  "I Want You (She´s So Heavy)", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=tAe2Q_LhY8g&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=6" },
{ name:  "Here Comes The Sun", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=xUNqsfFUwhY&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=7" },
{ name:  "Because", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=hL0tnrl2L_U&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=8" },
{ name:  "You Never Give Me Your Money", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=BpndGZ71yww&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=9" },
{ name:  "Sun King", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=6bNMxWGHlTI&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=10" },
{ name:  "Mean Mr. Mustard", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=oMarHac3VpQ&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=11" },
{ name:  "Polythene Pam", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=Cb0dTdTeHMU&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=12" },
{ name:  "She Came In Through The Bathroom Window", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=NVv7IzEVf3M&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=13" },
{ name:  "Golden Slumbers", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=AcQjM7gV6mI&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=14" },
{ name:  "Carry That Weight", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=6B224XDJw6g&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=15" },
{ name:  "The End", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=12R4FzIhdoQ&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=16" },
{ name:  "Her Majesty", album: "Abbey Road", artist: "The Beatles", link: "https://www.youtube.com/watch?v=Mh1hKt5kQ_4&list=PLycVTiaj8OI-kwvNjgvvopMJt__x-y5mD&index=17" },
{ name:  "Blitzkrieg Bop", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=skdE0KAFCEA&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=1" },
{ name:  "Beat On The Brat", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=GudM-IjhvSo&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=2" },
{ name:  "Judy Is A Punk", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=MXcjg9o9HJ8&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=3" },
{ name:  "I Wanna Be Your Boyfriend", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=BDvtkIp8UU4&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=4" },
{ name:  "Chain Saw", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=aka98A0Ekrw&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=5" },
{ name:  "Now I Wanna Sniff Some Glue", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=7l3U09uI3zE&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=6" },
{ name:  "I Don´t Wanna Go Down To The Basement", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=D3x8iz_Vr14&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=7" },
{ name:  "Loudmouth", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=tZ3v7VfZLGw&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=8" },
{ name:  "Havana Affair", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=FFFr2BIft-c&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=9" },
{ name:  "Listen To My Heart", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=BJkG1Fjo0Jw&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=10" },
{ name:  "53rd & 3rd", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=jJ_q5Zu3LSg&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=11" },
{ name:  "Let´s Dance", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=W3rynG8PF0I&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=12" },
{ name:  "I Don´t Wanna Walk Around With You", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=8fDOc6keM3w&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=13" },
{ name:  "Today Your Love, Tomorrow The World", album: "Ramones", artist: "The Ramones", link: "https://www.youtube.com/watch?v=Z5sBL18K7yU&list=PLBnJv6rImVe-LcbIsBXzIp6BpV6hqZnoO&index=14" },
{ name:  "Holidays In The Sun", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=xnNpY3KA6GM&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=1" },
{ name:  "Bodies", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=lWKhMTvpYk4&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=9" },
{ name:  "No Feelings", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=5QfHWNw7JZE&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=3" },
{ name:  "Liar", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=zP0WZ3Dbb4s&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=2" },
{ name:  "God Save The Queen", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=nA34XC08xHo&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=4" },
{ name:  "Problems", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=KDmuASzuJIo&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=5" },
{ name:  "Seventeen", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=J7qti6ycX3M&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=6" },
{ name:  "Anarchy In The U.K", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=jA51wUbivh0&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=7" },
{ name:  "Submission", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=quuZGzJuyVM&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=8" },
{ name:  "Pretty Vacant", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=vG2ZKxKVO_c&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=10" },
{ name:  "New York", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=WoK9g8WNTs8&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=11" },
{ name:  "EMI", album: "Never Mind the Bollocks, Here´s the Sex Pistols", artist: "Sex Pistols", link: "https://www.youtube.com/watch?v=yCsfTMk9gKo&list=PL8twFco4YVGLKRxVUgmLD5eoC4t7Lld2Z&index=12" },
{ name:  "Love´s In Need Of Love Today", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=FGZYWSfiYbM&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=1" },
{ name:  "Have A Talk With God", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=yQVeCxtuP14&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=2" },
{ name:  "Village Ghetto Land", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=B5xCZyIRCVM&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=3" },
{ name:  "Contusion", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=6T5q7BzpEe4&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=4" },
{ name:  "Sir Duke", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=6sIjSNTS7Fs&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=5" },
{ name:  "I Wish", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=dqVgGr_XfRM&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=6" },
{ name:  "Knocks Me Off My Feet", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=UwSuPXMHhaE&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=7" },
{ name:  "Pastime Paradise", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=b0S4SiLxt1s&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=8" },
{ name:  "Summer Soft", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=UDnwWkxEnMY&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=9" },
{ name:  "Ordinary Pain", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=SU0ClpWKqF8&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=10" },
{ name:  "Isn´t She Lovely", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=9-n3Ydy7ras&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=11" },
{ name:  "Joy Inside My Tears", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=TJ4bQfR7xBY&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=12" },
{ name:  "Black Man", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=pEoE2UQXduA&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=13" },
{ name:  "Ngiculela - Es Una Historia - I Am Singing", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=nJeJTVfNbFc&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=14" },
{ name:  "If It´s Magic", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=fX36mGEqfw4&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=15" },
{ name:  "As", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=GYQfWJNWe3I&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=16" },
{ name:  "Another Star", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=K9KKBvWTdMQ&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=17" },
{ name:  "Saturn", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=p3KpUO6t9qQ&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=18" },
{ name:  "Ebony Eyes", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=sqKyPQUReys&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=19" },
{ name:  "All Day Sucker", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=pz3rrESMnzI&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=20" },
{ name:  "Easy Goin´ Evening (My Mama´s Call)", album: "Songs in the Key of Life", artist: "Stevie Wonder", link: "https://www.youtube.com/watch?v=L0ZXSbUvWWs&list=PLjb5kMzP2zolSAPpMXR7_0MfYjEcDWQJO&index=21" },
{ name:  "Respect", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=9iayJ8u4Qew&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=1" },
{ name:  "Drown In My Own Tears", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=RH_vETRlYHY&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=2" },
{ name:  "I Never Loved A Man (The Way I Love You)", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=Ou2vVeRXO_s&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=3" },
{ name:  "Soul Serenade", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=XUjN1sMaJ-g&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=4" },
{ name:  "Don´t Let Me Lose This Dream", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=EZ-VZ8gpbr0&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=5" },
{ name:  "Baby, Baby, Baby", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=H5e0-X6RVTA&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=6" },
{ name:  "Dr. Feelgood", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=RjsfVVD2kaA&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=7" },
{ name:  "Good Times", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=ryDlxlMPWXw&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=8" },
{ name:  "Do Right Woman — Do Right Man", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=xJ5jnteCbdo&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=9" },
{ name:  "Save Me", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=cybMMmc6l74&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=10" },
{ name:  "A Change Is Gonna Come", album: "I Never Loved a Man the Way I Love You", artist: "Aretha Franklin", link: "https://www.youtube.com/watch?v=amVCS5ttGcE&list=PLCqS4xDDygMgpY9P3GJC5EPeioAQ_atro&index=11" },
{ name:  "Natural Mystic", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=gdlhMrHMcRc&list=PLA0FCD8C71A9FACD3&index=1" },
{ name:  "So Much Things To Say", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=vthzhg6GJuc&list=PLA0FCD8C71A9FACD3&index=2" },
{ name:  "Guiltiness", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=dnc8Bhgbj1E&list=PLA0FCD8C71A9FACD3&index=3" },
{ name:  "The Heathen", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=gRvBaDwoWBk&list=PLA0FCD8C71A9FACD3&index=4" },
{ name:  "Exodus", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=RSbqd7GkPq8&list=PLA0FCD8C71A9FACD3&index=5" },
{ name:  "Jamming", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=flZavyi6LW8&list=PLA0FCD8C71A9FACD3&index=6" },
{ name:  "Waiting In Vain", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=y8-m-W7mgjk&list=PLA0FCD8C71A9FACD3&index=7" },
{ name:  "Turn Your Lights Down Low", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=3kK8CwubWzQ&list=PLA0FCD8C71A9FACD3&index=8" },
{ name:  "Three Little Birds", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=-UfzGUgY11E&list=PLA0FCD8C71A9FACD3&index=9" },
{ name:  "One Love / People Get Ready", album: "Exodus", artist: "Bob Marley and The Wailers", link: "https://www.youtube.com/watch?v=-Sx7CjJ9_xU&list=PLA0FCD8C71A9FACD3&index=10" },
{ name:  "You Can Get It If You Really Want", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=Jg7qsW8qboE&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=1" },
{ name:  "Draw Your Brakes", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=pzL4G1KtwMc&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=2" },
{ name:  "Rivers Of Babylon", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=gnUKcEwT7NI&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=3" },
{ name:  "Many Rivers To Cross", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=fjW5f7i5EwE&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=4" },
{ name:  "And Dandy", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=kG-LQf_BCew&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=5" },
{ name:  "The Harder They Come", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=pmc5H6zAi6M&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=6" },
{ name:  "Johnny Too Bad", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=Sz_QVTejXdY&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=7" },
{ name:  "Shanty Town", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=alGOb2X9_ZY&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=8" },
{ name:  "Pressure Drop", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=px7LHI8D348&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=9" },
{ name:  "Sitting In Limbo", album: "The Harder They Come", artist: "Jimmy Cliff", link: "https://www.youtube.com/watch?v=-I7R8-g_G0Y&list=PLTZBRO2GYAOgN-O1hfyf7RooI5AGHq88X&index=10" },
{ name:  "Rocks Off", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=w5HP2Xcy_eQ&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=1" },
{ name:  "Rip This Joint", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=2C53QtZkwF8&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=2" },
{ name:  "Shake Your Hips", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=CfS19zxOBPc&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=3" },
{ name:  "Casino Boogie", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=deBu61SHBa0&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=4" },
{ name:  "Tumbling Dice", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=xcym7M1Obb8&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=5" },
{ name:  "Sweet Virginia", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=ZtplnF83hXM&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=6" },
{ name:  "Torn And Frayed", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=1Z-U2HUl7lg&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=7" },
{ name:  "Sweet Black Angel", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=Cwekn8dDxCo&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=8" },
{ name:  "Loving Cup", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=Nryc7h6TCIE&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=9" },
{ name:  "Happy", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=T9h3Hp4YrIY&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=10" },
{ name:  "Turd On The Run", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=nYFq26I8lvo&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=11" },
{ name:  "Ventilator Blues", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=SoxTSRV6XSc&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=12" },
{ name:  "I Just Want To See His Face", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=-anVr5LWA3U&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=13" },
{ name:  "Let It Loose", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=bnCkiNi_ssY&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=14" },
{ name:  "All Down The Line", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=rBLzORyYDgk&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=15" },
{ name:  "Stop Breaking Down", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=pgrplOjD6bY&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=16" },
{ name:  "Shine A Light", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=Vln9V7dDrIY&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=17" },
{ name:  "Soul Survivor", album: "Exile on Main St.", artist: "The Rolling Stones", link: "https://www.youtube.com/watch?v=7oElqYHn7p8&list=PLWYs5zVlt6JAZ_8G9PMtNvDlxGX08ZRHo&index=18" },
{ name:  "Black Dog", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=dIReHbOmU1U&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=1" },
{ name:  "Rock And Roll", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=4bv_ALKkTjQ&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=2" },
{ name:  "The Battle Of Evermore", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=pt2NrvdIY9E&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=3" },
{ name:  "Stairway To Heaven", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=CPSkNFODVRE&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=4" },
{ name:  "Misty Mountain Hop", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=Bb9pjvfLanY&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=5" },
{ name:  "Four Sticks", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=T8GP2j7NdSo&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=6" },
{ name:  "Going To California", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=0BYGM7UR--I&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=7" },
{ name:  "When The Levee Breaks", album: "IV", artist: "Led Zeppelin", link: "https://www.youtube.com/watch?v=NRUTJAO7uLE&list=PLnif9Rfb5Adk-e0rvMJgJIKqkANw3VfPm&index=8" },
{ name:  "The Good, The Bad And The Ugly", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=fzw34HKjfjU&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=1" },
{ name:  "The Sundown", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=2AslwRId1MM&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=2" },
{ name:  "The Strong", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=QtMmKZye1YY&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=3" },
{ name:  "The Desert", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=1Q-kVNHwIuY&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=4" },
{ name:  "The Carriage Of The Spirits", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=O9Dte3s5GNQ&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=5" },
{ name:  "Marcia", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=jvU1dOvq608&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=6" },
{ name:  "The Story Of A Soldier", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=8LUok8dMsSw&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=7" },
{ name:  "Marcia Without Hope", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=g_QKoZxxvwU&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=8" },
{ name:  "The Death Of A Soldier", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=otxTx-An7Ls&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=9" },
{ name:  "The Ecstasy Of Gold", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=lPdMDxh5ylc&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=10" },
{ name:  "The Trio - Main Title", album: "The Good, the Bad and the Ugly (Original Motion Picture Soundtrack)", artist: "Ennio Morricone", link: "https://www.youtube.com/watch?v=KPTjUVS57sk&list=PLmYc9gG3yj8QR9ea6_pTeS5oZJhf8Ffiw&index=11" },
{ name:  "Why So Serious?", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=pN_gYtqIgXs&list=PL2878AF2B65D2F1EA&index=1" },
{ name:  "I´m Not A Hero", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=p-8R9aq3N9E&list=PL2878AF2B65D2F1EA&index=2" },
{ name:  "Harvey Two-Face", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=l5BoY_IMLPg&list=PL2878AF2B65D2F1EA&index=3" },
{ name:  "Aggressive Expansion", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=jjDNn8qsCPI&list=PL2878AF2B65D2F1EA&index=4" },
{ name:  "Always A Catch", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=A8_sGoa_-88&list=PL2878AF2B65D2F1EA&index=5" },
{ name:  "Blood On My Hands", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=Gg1BK08G54g&list=PL2878AF2B65D2F1EA&index=6" },
{ name:  "A Little Push", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=-FUYR95Tla8&list=PL2878AF2B65D2F1EA&index=7" },
{ name:  "Like A Dog Chasing Cars", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=JQnHI7x0SyY&list=PL2878AF2B65D2F1EA&index=8" },
{ name:  "I Am The Batman", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=UZBZ9L_h-0E&list=PL2878AF2B65D2F1EA&index=9" },
{ name:  "And I Thought My Jokes Were Bad", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=Y3XyG0fhiDQ&list=PL2878AF2B65D2F1EA&index=10" },
{ name:  "Agent Of Chaos", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=xudMJ1oQDbk&list=PL2878AF2B65D2F1EA&index=11" },
{ name:  "Introduce A Little Anarchy", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=de1jSF_BXiI&list=PL2878AF2B65D2F1EA&index=12" },
{ name:  "Watch The World Burn", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=O4FPT3KQcmc&list=PL2878AF2B65D2F1EA&index=13" },
{ name:  "A Dark Knight", album: "The Dark Knight (Original Motion Picture Soundtrack)", artist: "Hans Zimmer", link: "https://www.youtube.com/watch?v=Gn2Qfz3sWXY" },
{ name:  "The God Delusion", album: "The God Delusion (Audiobook)", artist: "Richard Dawkins", link: "https://www.youtube.com/watch?v=1yW2pE2VvbE" },
{ name:  "A Doida", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=2SXJCQnvLqw&list=PLCE4104A542226382&index=7" },
{ name:  "Meu Parceiro", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=z5uRghM2C3E&list=PLCE4104A542226382&index=5" },
{ name:  "Véia", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=GF1hQpQFR0s&list=PLCE4104A542226382&index=6" },
{ name:  "Dois Beijinhos", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=ZnBnAOlKsLQ&list=PLCE4104A542226382&index=3" },
{ name:  "Vizinha", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=XBNU4Gp2QgY&list=PLCE4104A542226382&index=8" },
{ name:  "Amiga Da Minha Mulher", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=ENwJxGEIiDE&list=PLCE4104A542226382&index=1" },
{ name:  "Dia De Comemorar", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=LJwnyEJWr6k&list=PLCE4104A542226382&index=10" },
{ name:  "Japonesa", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=QelwvRzoxPs&list=PLCE4104A542226382&index=4" },
{ name:  "Olê, Olê", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=qO86X-MPlCc&list=PLCE4104A542226382&index=9" },
{ name:  "Quem Não Quer Sou Eu", album: "Músicas para Churrasco, Vol. 1", artist: "Seu Jorge", link: "https://www.youtube.com/watch?v=FHbBQi-332g&list=PLCE4104A542226382&index=2" },
{ name:  "Outras Palavras", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=YimR3XkT9Wo&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=1" },
{ name:  "Gema", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=CHZNkopduUQ&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=2" },
{ name:  "Vera Gata", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=BHSTGi2U0Aw&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=3" },
{ name:  "Lua E Estrela", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=YfTbodFOlIA&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=4" },
{ name:  "Sim // Não", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=9wqdNg-ZfU0&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=5" },
{ name:  "Nú Com A Minha Música", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=G-8ww0MCYbw&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=6" },
{ name:  "Rapte-Me Camaleoa", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=obxvhAnBSLM&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=7" },
{ name:  "Dans Mon Ile", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=FS55nsHXeK4&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=8" },
{ name:  "Tem Que Ser Você", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=1KhoIc9uGOA&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=9" },
{ name:  "Blues", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=S6H5a4TYlRI&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=10" },
{ name:  "Verdura", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=fEUTQgUky5s&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=11" },
{ name:  "Quero Um Baby Seu", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=3KKsRVtXgaE&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=12" },
{ name:  "Jeito De Corpo", album: "Outras Palavras", artist: "Caetano Veloso", link: "https://www.youtube.com/watch?v=3siR1bK7Gws&list=PLFAcddgaFN8x-PJYFQvr8xr_C8SIrhF36&index=13" },
];

function populateTable() {
    const tableBody = document.querySelector("#myTable tbody");

    tableBody.innerHTML = '';

    data.forEach(music => {
        const row = tableBody.insertRow();
        const cell1 = row.insertCell(0);
        const cell2 = row.insertCell(1);
        const cell3 = row.insertCell(2);
        const cell4 = row.insertCell(3);

        cell1.textContent=music.name;
        cell2.textContent=music.album;
        cell3.textContent=music.artist;
        cell4.innerHTML=`<a href="${music.link}" target="_blank">${music.link}</a>`;
    });
}
